"""Tests for envdiff.templater."""

from __future__ import annotations

import os
import pytest

from envdiff.comparator import CompareResult, KeyDiff
from envdiff.templater import TemplateError, TemplateOptions, generate_template, write_template


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _write(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(content)


def _result(*diffs: KeyDiff) -> CompareResult:
    return CompareResult(diffs=list(diffs))


# ---------------------------------------------------------------------------
# generate_template from file path
# ---------------------------------------------------------------------------

def test_template_from_file_contains_keys(tmp_path):
    env = tmp_path / "app.env"
    _write(str(env), "FOO=bar\nBAZ=qux\n")
    content = generate_template(str(env))
    assert "FOO=" in content
    assert "BAZ=" in content


def test_template_from_file_no_values_by_default(tmp_path):
    env = tmp_path / "app.env"
    _write(str(env), "FOO=secret\n")
    content = generate_template(str(env))
    assert "secret" not in content
    assert "FOO=" in content


def test_template_from_file_include_values(tmp_path):
    env = tmp_path / "app.env"
    _write(str(env), "FOO=secret\n")
    opts = TemplateOptions(include_values=True)
    content = generate_template(str(env), opts)
    assert "FOO=secret" in content


def test_template_sorted_by_default(tmp_path):
    env = tmp_path / "app.env"
    _write(str(env), "ZZZ=1\nAAA=2\n")
    content = generate_template(str(env))
    lines = [l for l in content.splitlines() if "=" in l]
    assert lines[0].startswith("AAA")
    assert lines[1].startswith("ZZZ")


def test_template_placeholder_used(tmp_path):
    env = tmp_path / "app.env"
    _write(str(env), "KEY=val\n")
    opts = TemplateOptions(placeholder="CHANGEME")
    content = generate_template(str(env), opts)
    assert "KEY=CHANGEME" in content


# ---------------------------------------------------------------------------
# generate_template from CompareResult
# ---------------------------------------------------------------------------

def test_template_from_result_includes_all_keys():
    result = _result(
        KeyDiff(key="A", left_value="1", right_value=None),
        KeyDiff(key="B", left_value=None, right_value="2"),
        KeyDiff(key="C", left_value="x", right_value="y"),
    )
    content = generate_template(result)
    for key in ("A", "B", "C"):
        assert f"{key}=" in content


def test_template_header_present_by_default(tmp_path):
    env = tmp_path / "a.env"
    _write(str(env), "X=1\n")
    content = generate_template(str(env))
    assert "Generated by envdiff" in content


def test_template_no_header_when_disabled(tmp_path):
    env = tmp_path / "a.env"
    _write(str(env), "X=1\n")
    opts = TemplateOptions(comment_header="")
    content = generate_template(str(env), opts)
    assert "Generated by envdiff" not in content


def test_template_extra_keys_added(tmp_path):
    env = tmp_path / "a.env"
    _write(str(env), "EXISTING=1\n")
    opts = TemplateOptions(extra_keys=["NEW_KEY"])
    content = generate_template(str(env), opts)
    assert "NEW_KEY=" in content
    assert "EXISTING=" in content


def test_template_invalid_source_raises():
    with pytest.raises(TemplateError):
        generate_template(42)  # type: ignore


# ---------------------------------------------------------------------------
# write_template
# ---------------------------------------------------------------------------

def test_write_template_creates_file(tmp_path):
    out = tmp_path / "out" / "result.env"
    write_template("KEY=\n", str(out))
    assert out.exists()
    assert out.read_text() == "KEY=\n"
