"""CLI sub-commands for the templater feature."""

from __future__ import annotations

import argparse
import sys

from envdiff.differ import diff_files
from envdiff.templater import TemplateError, TemplateOptions, generate_template, write_template


def add_templater_subcommands(subparsers: argparse._SubParsersAction) -> None:  # noqa: SLF001
    p = subparsers.add_parser(
        "template",
        help="Generate a .env template from a file or diff of two files.",
    )
    p.add_argument("left", help="Primary .env file (or left side of diff).")
    p.add_argument("right", nargs="?", default=None, help="Optional right .env file for diff-based template.")
    p.add_argument("-o", "--output", default=None, help="Write template to this path instead of stdout.")
    p.add_argument("--include-values", action="store_true", help="Include actual values from the left file.")
    p.add_argument("--placeholder", default="", help="Placeholder value for keys without a value.")
    p.add_argument("--no-header", action="store_true", help="Omit the generated-by comment header.")
    p.add_argument("--no-sort", action="store_true", help="Preserve key order instead of sorting.")
    p.add_argument("--add-key", metavar="KEY", action="append", dest="extra_keys", default=[], help="Extra key to add.")
    p.set_defaults(func=_cmd_template)


def _cmd_template(args: argparse.Namespace) -> int:
    options = TemplateOptions(
        include_values=args.include_values,
        placeholder=args.placeholder,
        comment_header="" if args.no_header else "# Generated by envdiff",
        sort_keys=not args.no_sort,
        extra_keys=args.extra_keys or [],
    )

    try:
        if args.right:
            result = diff_files(args.left, args.right)
            content = generate_template(result, options)
        else:
            content = generate_template(args.left, options)
    except TemplateError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.output:
        try:
            write_template(content, args.output)
            print(f"Template written to {args.output}")
        except OSError as exc:
            print(f"error: cannot write output: {exc}", file=sys.stderr)
            return 1
    else:
        print(content, end="")

    return 0
