"""Generate .env template files from compare results or existing env files."""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from envdiff.comparator import CompareResult
from envdiff.parser import parse_env_file


class TemplateError(Exception):
    """Raised when template generation fails."""


@dataclass
class TemplateOptions:
    include_values: bool = False
    placeholder: str = ""
    comment_header: str = "# Generated by envdiff"
    sort_keys: bool = True
    extra_keys: List[str] = field(default_factory=list)


def generate_template(
    source: CompareResult | str,
    options: Optional[TemplateOptions] = None,
) -> str:
    """Return a .env template string.

    *source* may be a :class:`CompareResult` (all keys from both sides are
    included) or a path to an existing .env file.
    """
    if options is None:
        options = TemplateOptions()

    if isinstance(source, str):
        keys = _keys_from_file(source)
        values: Dict[str, str] = _values_from_file(source) if options.include_values else {}
    elif isinstance(source, CompareResult):
        keys = _keys_from_result(source)
        values = _values_from_result(source) if options.include_values else {}
    else:
        raise TemplateError(f"Unsupported source type: {type(source)}")

    all_keys = sorted(set(keys) | set(options.extra_keys)) if options.sort_keys else list(keys)

    lines: List[str] = []
    if options.comment_header:
        lines.append(options.comment_header)
        lines.append("")

    for key in all_keys:
        value = values.get(key, options.placeholder)
        lines.append(f"{key}={value}")

    return "\n".join(lines) + "\n"


def write_template(content: str, output_path: str) -> None:
    """Write *content* to *output_path*, creating parent directories as needed."""
    parent = os.path.dirname(output_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _keys_from_file(path: str) -> List[str]:
    try:
        return list(parse_env_file(path).keys())
    except Exception as exc:
        raise TemplateError(f"Cannot read env file '{path}': {exc}") from exc


def _values_from_file(path: str) -> Dict[str, str]:
    try:
        return dict(parse_env_file(path))
    except Exception as exc:
        raise TemplateError(f"Cannot read env file '{path}': {exc}") from exc


def _keys_from_result(result: CompareResult) -> List[str]:
    keys = set()
    for diff in result.diffs:
        keys.add(diff.key)
    return list(keys)


def _values_from_result(result: CompareResult) -> Dict[str, str]:
    values: Dict[str, str] = {}
    for diff in result.diffs:
        if diff.left_value is not None:
            values[diff.key] = diff.left_value
        elif diff.right_value is not None:
            values[diff.key] = diff.right_value
    return values
